version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    environment:
      CI: false
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting 
workflows:
    build-test-deploy:
      jobs:
        - build-test-deploy:
            requires:
              - build
            filters:
              branches:
                only: master

            
